id: A03EB57FF
title: A Simple Practice of Phowa, 'Transference of Consciousness'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:57:17.897230
  last_modified_at: 2022-03-01 01:57:17.897234
